name: 部署至 GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 檢出專案碼
        uses: actions/checkout@v4

      - name: 安裝 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安裝依賴
        run: npm ci

      - name: 執行 Vite 打包建置
        run: npm run build

      - name: 上傳 Pages 構建產物
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: 部署至 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
